---
title: "Ms_2"
author: "Gabe Cederberg"
date: "2/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**First Project: "Harvard Dining" by Neil Khurana**

I am generally quite interested in the logistics of running HUDS, so this project appeals to me. Some of the major PROS of this project are that (1) it is very easy to understand all of the figures; they do not need much complex explanation, (2) the website looks very clean; nothing is too distracting; and (3) they clearly put in a lot of work to gather and clean this data. I'm sure that took a lot of effort and it seems that they did a good job! 

However, this project does leave me wanting a little more. For example, it's a little unsatisfying that 'Cilantro' is the most commonly served food during dinners. I think it could've been more effective to break the foods up into their respective categories, like entrees, salad bar, plant protein, etc. and then allow website users to see the most common foods from *within* each of those categories. Maybe that's just a personal thing. Also, the second tab in the project is "Calendar" which simply allows you to see the foods that were offered on a single given day of your choice. While that would be helpful if I'm trying to track down what was served on a particular day, it doesn't really give me any insights into the nature of the HUDS operation. Maybe this could've been a later tab. I also think I want to know a little more about the person doing the project and what their scraping process looked like. 


**Second Project: "Fatalities in Yemen’s Civil War" by Liz Masten**

The second project I looked at caught my eye because I did a final project on the Civil War in Yemen last semester using GIS software, and I think this dataset that Liz used would've probably been super helpful. I think the biggest pros of the project are that it flows really well, it effectively communicates a TON of data, it shows that data really well on a map, and it's able to back up the visualizations with a deep explanation of the methodology behind it and an analysis of the different terms / actors that the project covers. 

That said, I think some of the figures look smushed on my browser, so I'm not sure if they didn't knit well or something. Also, according to the Methodology section she included the Houthi rebel forces in the "Yemeni Government" category, which to me seems wrong because the insurgent Houthis are fighting *against* the Royal Government forces. I also get a little nervous when the project creator attaches fatality correlations to certain groups, because I think it could be used to justify criticizing one group over another when the data is likely incomplete and could mislead third party decision-makers in trying to place blame. Overall, I think this is a really cool project and I'm glad Liz took on such a complex and difficult topic with a large (probably unwieldy) dataset. 

**Link to my GitHub repo for this Milestone:**
https://github.com/GabeCeder/Ms_2